pivnet-api-token: 34042306c1994e589930a08871e17ee3
pivnet-file-glob: "*pivotal"
pivnet-product-slug: "pivotal-container-service"
product-version: "1.4.0"
download-stemcell: true
stemcell-iaas: "google"
